services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: collectorshub_app_dev
    restart: unless-stopped
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - /var/www/html/node_modules
    environment:
      - APP_NAME=CollectorsHub
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS="hello@example.com"
      - MAIL_FROM_NAME="${APP_NAME}"
      
      - VITE_APP_NAME="${APP_NAME}"
    networks:
      - collectorshub_network
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: collectorshub_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - collectorshub_network

  redis:
    image: redis:7-alpine
    container_name: collectorshub_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - collectorshub_network

networks:
  collectorshub_network:
    driver: bridge

volumes:
  redis_data:
    driver: local 