name: Auto Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
      - name: Install dependencies
        run: npm install
        
      - name: Get changed files
        id: changed-files-js
        uses: tj-actions/changed-files@v46
        with:
          files: |
            resources/js/**/*.{js,ts,vue}
      
      - name: Run ESLint on changed files
        if: steps.changed-files-js.outputs.any_changed == 'true'
        run: |
          echo "Linting changed files:"
          echo "${{ steps.changed-files-js.outputs.all_changed_files }}"
          npx eslint ${{ steps.changed-files-js.outputs.all_changed_files }}

  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none
          extensions: mbstring, dom, fileinfo
          
      - name: Validate composer.json
        run: composer validate --strict
        
      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-
            
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        
      - name: Get changed files
        id: changed-files-php
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.php
            
      - name: Run PHP CS Fixer on changed files
        if: steps.changed-files-php.outputs.any_changed == 'true'
        run: |
          echo "Checking changed files:"
          echo "${{ steps.changed-files-php.outputs.all_changed_files }}"
          vendor/bin/php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.php ${{ steps.changed-files-php.outputs.all_changed_files }} 